module.exports={
    isAdmin:(req,res,next)=>{
        if(req.session.adminLogin){
            next()
        }else{
            res.redirect('/')
        }
    },
    isUser:(req,res,next)=>{
        if(req.session.user){
            next()
        }else{
            res.redirect('/login')
        }
    }
}